### ISSUE TITLE
rangeland_production

### ISSUE THREAD

**Issue by phargogh** [natcap/mercurial-migration-plan#12]
URL of the original repo: https://bitbucket.org/natcap/rangeland_production

* Who's the repo maintainer?
    * @vakowal 
* How much of the source tree should be migrated?
    * TBD
* Are there issues to migrate?
    * There are issues.  @vakowal , would you like for these to be migrated?
* Is there a wiki to migrate?
    * No.
* Should issue numbers be prefixed in the source tree?
    * Probably?
* Does this repo require CI services?
    * Repo currently uses bitbucket pipelines for building and deployment.  May be more practical to keep the repo on bitbucket for the sake of pipelines.

@vakowal, let's talk sometime about what to do about this repository!

**Comment by phargogh** [comment]
OK!  So, here's what @vakowal and I talked about today for this repo:

* We'll finish the one outstanding PR for this project before converting
* I'll take care of the conversion via `hg-fast-export` (maintaining original issue numbers)
* @vakowal will copy over the text of the issues that exist for the project
* When I push the new branches over, `develop` and `feature/FORAGE-MODEL-18-python27to36-compatibility` are the only two that matter.  All others do not need to be pushed.

**Comment by phargogh** [comment]
OK!  @vakowal sorry about the delay here.  I've converted and pushed the rangelands repo to https://github.com/natcap/rangeland_production, keeping only the two branches noted in the comment above.  I've also added you as a maintainer on the repo, so you should be able to make changes as you see fit.

**Comment by vakowal** [comment]
thanks @phargogh !  I'll copy over issues from bitbucket and then archive the bitbucket repo, notifying folks who end up there that they should come here to github instead. Sound good to you?

**Comment by phargogh** [comment]
Sounds good to me!  Either work, and bitbucket will be deleting the repository in about 6 months anyways.  Personally, I've been updating the repository description with a link to the new repo when I'm finishing a migration.  Deleting the repo also works, though, and bitbucket allows you to provide a link to the code's new home.  Either way sounds ok by me!

And, FWIW, I've backed up the hg repo and issues to a shared google drive for safe keeping :)

**Comment by phargogh** [comment]
Whoops ... didn't mean to close the issue!

**Comment by vakowal** [comment]
done! and closed. Thanks James!
