### ISSUE TITLE
optimizat

### ISSUE THREAD

**Issue by phargogh** [natcap/mercurial-migration-plan#63]
URL of the original repo: https://bitbucket.org/natcap/optimizat

* Who's the repo maintainer?
    * @vakowal and others
* How much of the source tree should be migrated?
    * Need to ask the maintainers
* Are there issues to migrate?
    * No
* Is there a wiki to migrate?
    * No
* Should issue numbers be prefixed in the source tree?
    * No issues
* Does this repo require CI services?
    * No

This looks like work that was done for a study and then not used since.

It's a git repo as well, so there's no immediate need to migrate.  That might be the answer for this repo.

**Comment by vakowal** [comment]
Thanks @phargogh!  Optimizat is not worth keeping, all the good stuff was migrated to vakowal/ES_optimization when the paper was published.  Let's delete Optimizat.

**Comment by phargogh** [comment]
OK!  I've backed up optimizat via `git buncle create optimizat.bundle --all`, deleted the repo on bitbucket and added a link to the new repo at https://github.com/vakowal/ES_optimization.

And with that, I think we're done!  Thanks for your help, @vakowal!
